name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MySQL
        uses: mysql-actions/setup-mysql@v2
        with:
          mysql-version: '8.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mysql-connector-python

      - name: Set up MySQL Database
        run: |
          mysql -e "CREATE DATABASE test_db;"
          
      - name: Run SQL file
        run: |
          mysql test_db < path_to_your_sql_file.sql
          
      - name: Run unit tests
        run: |
          python3 -m unittest discover -s tests
