name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MySQL with Docker
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -d mysql:8.0

      - name: Wait for MySQL to start
        run: |
          sleep 30  # Wait for the MySQL container to fully start

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mysql-connector-python

      - name: Set up MySQL Database
        run: |
          docker exec -i mysql-container mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS test_db;"
          docker exec -i mysql-container mysql -u root -proot test_db < ./A2.sql  # Make sure the path to your SQL file is correct

      - name: Run unit tests
        run: |
          python3 -m unittest discover -s . -p "test_*.py"  # Adjust if needed

      - name: Clean up
        run: |
          docker stop mysql-container
          docker rm mysql-container
